# Generated by Django 4.0.6 on 2022-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_description', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
