# Generated by Django 4.0.6 on 2022-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_banner',
            field=models.TextField(null=True),
        ),
    ]
