# Generated by Django 4.0.6 on 2022-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_tracks_track_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_banner',
            field=models.ImageField(blank=True, null=True, upload_to='trackImages/'),
        ),
    ]
