# Generated by Django 4.0.6 on 2022-08-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_tour_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
